FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    git build-essential libpq-dev python3-dev \
 && rm -rf /var/lib/apt/lists/*

# Pinner versions stables et compatibles
RUN pip install --no-cache-dir "dbt-core==1.10.13" "dbt-postgres==1.10.13"

WORKDIR /usr/app



